version: '3'
services:
  poc_open62541:
    image: poc.open62541:1.4.1
    volumes:
      - type: bind
        source: ${PWD}/src
        target: /src
    command: ["bash", "/src/open62541/build_and_run.sh", "server"]
  # poc_open62541_client:
  #   image: poc.open62541:1.4.1
  #   volumes:
  #     - type: bind
  #       source: ${PWD}/src
  #       target: /src
  #   command: ["bash", "/src/open62541/build_and_run.sh", "client"]
  # poc_freeopcua:
  #   image: poc.freeopcua
  #   volumes:
  #     - type: bind
  #       source: ${PWD}/src
  #       target: /src
  #   command: ["python", "/src/freeopcua/sync/server-minimal.py"]
  poc_s2opc:
    image: poc.s2opc:${S2OPC_VERSION}
    volumes:
      - type: bind
        source: ${PWD}/src
        target: /src
    command: ["bash", "/src/S2OPC/build_and_run.sh"]
