FROM registry.gitlab.com/systerel/s2opc/build:1.42

# Copy library
COPY . /opt/S2OPC

# Create a build directory
WORKDIR /opt/S2OPC

# Configure and build the library
RUN bash clean.sh && bash build.sh

WORKDIR /opt/S2OPC/build

RUN make install

# Setup profile
RUN echo 'alias ll="ls -l"' > ~/.bashrc

RUN apt-get update \
    && apt-get install -y apt-utils \
    && apt-get install -y ca-certificates \
    && apt-get install -y iputils-ping \
    && apt-get install -y dnsutils \
    && apt-get install -y net-tools \
    && apt-get install -y iproute2 \
    && apt-get install -y procps \
    && apt-get install -y vim \
    && apt-get install -y bash \
    && apt-get install -y curl \
    && apt-get install -y less \
    && apt-get install -y lsof \
    && apt-get install -y telnet \
    && apt-get install -y tcpdump \
    && apt-get clean

# Set the default command to run a shell
CMD ["bash"]
